FROM golang:alpine AS builder


WORKDIR $GOPATH/src/github.com/xfoxawy/catchall-domain
COPY . .

RUN go get -d -v

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/catchall-domain

FROM alpine:latest

COPY --from=builder /go/bin/catchall-domain /go/bin/catchall-domain

EXPOSE 80

ENTRYPOINT ["/go/bin/catchall-domain" , "serve-http"]
